### ISSUE TITLE
Add timer and remainder feature

### ISSUE THREAD

**Issue by sanjanabagodi** [AB-Law/alfred-discord-bot#2]
**Timer feature:**
After the set time, the bot should ping the user who set the timer and display the comment. By default, it should display nothing(?)
_syntax:_
_timer time(in hours and minutes) comment(optional)
_ex:_
_timer 1h 30m study time

**Remainder feature:** 
The bot should ping the user and display the comment on the given date and time. 
_syntax:_
_remainder dd/mm/yyyy  time(in 24hr format) comment
_ex:_
_remainder 26/01/2021 18:00 meh

It would be nice if the bot can DM the remainders and timers to the user. Also if we can use _today_ and _tomorrow_ or _tom_ instead of date.

**Comment by AB-Law** [comment]
Since there has been no further progress on this issue, I've written the code for this and will create a pull request to fix this issue.
Thanks for the feature request @sanjanabagodi
